apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp-deployment
spec:
  replicas: 7
  selector:
    matchLabels:
      app: helloapp
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
      - name: app
        image: helloapp:latest
        ports:
        - containerPort: 5000
      - name: sidecar
        image: busybox
        command: ['sh', '-c', 'while true; do echo $(date) Sample log from sidecar container; sleep 10; done']
