apiVersion: apps/v1
kind: Deployment
metadata:
  name: prodapp
spec:
  replicas: 7
  selector:
    matchLabels:
      app: prodapp
  template:
    metadata:
      labels:
        app: prodapp
    spec:
      containers:
      - name: app
        image: duaraghav8/log-generator:0.0.2
        ports:
        - containerPort: 5000
      - name: auth-agent
        image: duaraghav8/sidecar:0.0.1
