apiVersion: apps/v1
kind: Deployment
metadata:
  name: prodapp
spec:
  replicas: 7
  selector:
    matchLabels:
      app: prodapp
  template:
    metadata:
      labels:
        app: prodapp
    spec:
      containers:
      - name: app
        image: duaraghav8/log-generator:latest
        ports:
        - containerPort: 5000
      - name: sidecar
        image: busybox
        command: ['sh', '-c', 'while true; do echo $(date) Sample log from sidecar container; sleep 10; done']
