apiVersion: v1
kind: Service
metadata:
  name: service-a
spec:
  ports:
    - port: 5000
  selector:
    app: service-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a
spec:
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a
        image: duaraghav8/flask_service_a:latest
        ports:
        - containerPort: 5000